import { describe, expect, test } from "vitest";
import {
  loadProjectInMemory,
  newProject,
  saveProjectToDirectory,
} from "@inlang/sdk";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { plugin, PLUGIN_KEY } from "./plugin.js";

const settings = {
  baseLocale: "en",
  locales: ["en", "de"],
  modules: [],
  [PLUGIN_KEY]: { pathPattern: "./Localizations/Localizable.xcstrings" },
};
const path = "./Localizations/Localizable.xcstrings";

/**
 * A catalog as Xcode writes it: ` : ` separators, two spaces, no final
 * newline, strings and locales sorted by code units, `comment`,
 * `extractionState` and `state` values that the plugin doesn't write,
 * implicit printf arguments.
 */
const xcode = `{
  "sourceLanguage" : "en",
  "strings" : {
    "%lld items" : {
      "localizations" : {
        "de" : {
          "variations" : {
            "plural" : {
              "one" : {
                "stringUnit" : {
                  "state" : "translated",
                  "value" : "%lld Artikel"
                }
              },
              "other" : {
                "stringUnit" : {
                  "state" : "translated",
                  "value" : "%lld Artikel"
                }
              }
            }
          }
        },
        "en" : {
          "variations" : {
            "plural" : {
              "one" : {
                "stringUnit" : {
                  "state" : "new",
                  "value" : "%lld item"
                }
              },
              "other" : {
                "stringUnit" : {
                  "state" : "new",
                  "value" : "%lld items"
                }
              }
            }
          }
        }
      }
    },
    "Zebra %@" : {
      "comment" : "Shown on the \\"zoo\\" screen",
      "extractionState" : "extracted_with_value",
      "localizations" : {
        "de" : {
          "stringUnit" : {
            "state" : "needs_review",
            "value" : "Zebra %@ \\u00fc"
          }
        },
        "en" : {
          "stringUnit" : {
            "state" : "new",
            "value" : "Zebra %@"
          }
        }
      }
    },
    "apple" : {
      "localizations" : {
        "de" : {
          "stringUnit" : {
            "state" : "translated",
            "value" : "Apfel"
          }
        },
        "en" : {
          "stringUnit" : {
            "state" : "translated",
            "value" : "Apple"
          }
        }
      }
    },
    "cart" : {
      "comment" : "Items in the cart",
      "isCommentAutoGenerated" : true,
      "localizations" : {
        "en" : {
          "stringUnit" : {
            "state" : "translated",
            "value" : "You have %#@items@"
          },
          "substitutions" : {
            "items" : {
              "argNum" : 1,
              "formatSpecifier" : "lld",
              "variations" : {
                "plural" : {
                  "one" : {
                    "stringUnit" : {
                      "state" : "translated",
                      "value" : "%lld item"
                    }
                  },
                  "other" : {
                    "stringUnit" : {
                      "state" : "translated",
                      "value" : "%lld items"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "learn_more" : {
      "extractionState" : "manual",
      "localizations" : {
        "en" : {
          "variations" : {
            "device" : {
              "iphone" : {
                "stringUnit" : {
                  "state" : "translated",
                  "value" : "Tap  to learn more"
                }
              },
              "other" : {
                "stringUnit" : {
                  "state" : "translated",
                  "value" : "Click to learn more"
                }
              }
            }
          }
        }
      }
    }
  },
  "version" : "1.0"
}`;

describe("export with the existing catalog", () => {
  test("an Xcode catalog without edits is written byte for byte", async () => {
    expect(await reexport(xcode)).toBe(xcode);
  });

  test("CRLF, a byte order mark and a final newline are kept", async () => {
    const previous = "\uFEFF" + xcode.replace(/\n/g, "\r\n") + "\r\n";
    expect(await reexport(previous)).toBe(previous);
  });

  test("hand-written JSON with odd whitespace, escapes and key order is kept", async () => {
    const previous =
      '{"version":"1.0",   "strings": {"b":{"localizations":{"en":{"stringUnit":{"value":"B \\/ \\u0042","state":"translated"}}}},\n' +
      '\t"a" :{"localizations":{"en":{"stringUnit":{"value":"A","state":"translated"}}}}},"sourceLanguage":"en"}';
    expect(await reexport(previous)).toBe(previous);
  });

  test("editing one translation only changes its value", async () => {
    const output = await reexport(xcode, (data) => {
      setText(data, "Zebra %@", "de", "Zebra %1$@ ö");
    });
    expect(output).toBe(xcode.replace('"Zebra %@ \\u00fc"', '"Zebra %1$@ ö"'));
  });

  test("editing a plural variant only changes that variant", async () => {
    const output = await reexport(xcode, (data) => {
      setText(data, "%lld items", "de", "%1$lld Stück", "one");
    });
    // the first occurrence is the `one` variant of `de`
    expect(output).toBe(xcode.replace('"%lld Artikel"', '"%1$lld Stück"'));
  });

  test("editing a substitution whose template has text around it rewrites only that string", async () => {
    // The plugin moves the text around `%#@items@` into the variants, so the
    // kept template and an edited variant don't import to the new message.
    const output = await reexport(xcode, (data) => {
      setText(data, "cart", "en", "You have %1$lld items!", "other");
    });
    const cart = (text: string) =>
      text.slice(
        text.indexOf('    "cart" : {'),
        text.indexOf('    "learn_more"'),
      );
    expect(output).toBe(
      xcode.replace(
        cart(xcode),
        cart(xcode)
          .replace(
            '"comment" : "Items in the cart",',
            '"comment" : "Items in the cart",\n      "extractionState" : "manual",',
          )
          .replace('"You have %#@items@"', '"%#@items@"')
          .replace('"%lld item"', '"You have %1$lld item"')
          .replace('"%lld items"', '"You have %1$lld items!"'),
      ),
    );
  });

  test("a change of only whitespace inside a pattern is written", async () => {
    const output = await reexport(xcode, (data) => {
      setText(data, "learn_more", "en", "Tap to learn more", "iphone");
    });
    expect(output).toBe(
      xcode.replace('"Tap  to learn more"', '"Tap to learn more"'),
    );
  });

  test("a change of only a placeholder is written", async () => {
    const output = await reexport(xcode, (data) => {
      const variant = findVariant(data, "Zebra %@", "en");
      const expression = variant.pattern[1];
      expression.annotation.options = [
        { name: "specifier", value: { type: "literal", value: "lld" } },
        { name: "position", value: { type: "literal", value: "1" } },
      ];
    });
    expect(output).toBe(
      xcode.replace('"value" : "Zebra %@"', '"value" : "Zebra %1$lld"'),
    );
  });

  test("a new message is inserted in sorted position, a removed message is dropped", async () => {
    const output = await reexport(xcode, (data) => {
      removeBundle(data, "apple");
      data.bundles.push({ id: "banana", declarations: [] });
      data.messages.push({
        id: "banana-en",
        bundleId: "banana",
        locale: "en",
        selectors: [],
      });
      data.variants.push({
        id: "banana-en-variant",
        messageId: "banana-en",
        matches: [],
        pattern: [{ type: "text", value: "Banana" }],
      });
    });
    const apple = xcode.slice(
      xcode.indexOf('    "apple" : {'),
      xcode.indexOf('    "cart" : {'),
    );
    // The members of a new value are written by `JSON.stringify` (`": "`),
    // not with Xcode's ` : `.
    expect(output).toBe(
      xcode.replace(
        apple,
        [
          '    "banana" : {',
          '      "extractionState": "manual",',
          '      "localizations": {',
          '        "en": {',
          '          "stringUnit": {',
          '            "state": "translated",',
          '            "value": "Banana"',
          "          }",
          "        }",
          "      }",
          "    },",
          "",
        ].join("\n"),
      ),
    );
  });

  test("a new translation of an existing message is added to the message", async () => {
    const output = await reexport(xcode, (data) => {
      data.messages.push({
        id: "learn_more-de",
        bundleId: "learn_more",
        locale: "de",
        selectors: [{ type: "variable-reference", name: "device" }],
      });
      data.variants.push({
        id: "learn_more-de-other",
        messageId: "learn_more-de",
        matches: [{ type: "catchall-match", key: "device" }],
        pattern: [{ type: "text", value: "Klicken" }],
      });
    });
    expect(output).toBe(
      xcode.replace(
        '      "localizations" : {\n        "en" : {\n          "variations"',
        [
          '      "localizations" : {',
          '        "de" : {',
          '          "variations": {',
          '            "device": {',
          '              "other": {',
          '                "stringUnit": {',
          '                  "state": "translated",',
          '                  "value": "Klicken"',
          "                }",
          "              }",
          "            }",
          "          }",
          "        },",
          '        "en" : {',
          '          "variations"',
        ].join("\n"),
      ),
    );
  });

  test("comments of strings are kept, also if the whole catalog is written", async () => {
    // a previous file that the plugin can't keep: the edited message is
    // written as a whole, the comments of all strings are kept
    const previous = JSON.stringify(JSON.parse(xcode));
    const data = await importCatalog(previous);
    removeBundle(data, "apple");
    const [file] = await plugin.exportFiles!({
      settings,
      ...data,
      files: [{ path, locale: "en", content: encode(previous) }],
    });
    const catalog = JSON.parse(decode(file!.content));
    expect(catalog.strings.cart.comment).toBe("Items in the cart");
    expect(catalog.strings.cart.isCommentAutoGenerated).toBe(true);
    expect(catalog.strings["Zebra %@"].comment).toBe(
      'Shown on the "zoo" screen',
    );
    expect(catalog.strings.apple).toBeUndefined();
  });

  test("prototype-looking keys are kept and removed like other keys", async () => {
    const previous = `{
  "sourceLanguage" : "en",
  "strings" : {
    "__proto__" : {
      "comment" : "p",
      "localizations" : {
        "en" : {
          "stringUnit" : {
            "state" : "translated",
            "value" : "Proto"
          }
        }
      }
    },
    "constructor" : {
      "localizations" : {
        "en" : {
          "stringUnit" : {
            "state" : "translated",
            "value" : "Constructor"
          }
        }
      }
    }
  },
  "version" : "1.0"
}`;
    expect(await reexport(previous)).toBe(previous);
    const output = await reexport(previous, (data) => {
      removeBundle(data, "constructor");
      setText(data, "__proto__", "en", "Prototype");
    });
    const edited = previous.replace('"Proto"', '"Prototype"');
    expect(output).toBe(
      edited.slice(0, edited.indexOf(',\n    "constructor"')) +
        '\n  },\n  "version" : "1.0"\n}',
    );
  });

  test("no existing file writes the full export as before", async () => {
    const data = await importCatalog(
      '{"sourceLanguage":"en","version":"1.0","strings":{"b":{"comment":"c","localizations":{"en":{"stringUnit":{"state":"new","value":"B %@"}}}},' +
        '"a":{"localizations":{"de":{"stringUnit":{"state":"translated","value":"A"}}}}}}',
    );
    const [withoutFiles] = await plugin.exportFiles!({ settings, ...data });
    const [withEmptyFiles] = await plugin.exportFiles!({
      settings,
      ...data,
      files: [],
    });
    expect(decode(withEmptyFiles!.content)).toBe(decode(withoutFiles!.content));
    expect(decode(withoutFiles!.content)).toBe(`{
  "sourceLanguage": "en",
  "strings": {
    "a": {
      "extractionState": "manual",
      "localizations": {
        "de": {
          "stringUnit": {
            "state": "translated",
            "value": "A"
          }
        }
      }
    },
    "b": {
      "extractionState": "manual",
      "localizations": {
        "en": {
          "stringUnit": {
            "state": "translated",
            "value": "B %1$@"
          }
        }
      }
    }
  },
  "version": "1.0"
}
`);
  });

  test("an invalid existing file writes the full export", async () => {
    const data = await importCatalog(xcode);
    const [full] = await plugin.exportFiles!({ settings, ...data });
    for (const invalid of [
      "{ not json",
      "[]",
      '{"sourceLanguage":"fr","strings":{},"version":"1.0"}',
    ]) {
      const [file] = await plugin.exportFiles!({
        settings,
        ...data,
        files: [{ path, locale: "en", content: encode(invalid) }],
      });
      expect(decode(file!.content)).toBe(decode(full!.content));
    }
  });

  test("a catalog written by the full export keeps its order and formatting", async () => {
    // e.g. saved by an earlier version of the plugin
    const data = await importCatalog(xcode);
    const [full] = await plugin.exportFiles!({ settings, ...data });
    const previous = decode(full!.content);
    const output = await reexport(previous, (data) => {
      setText(data, "apple", "de", "Äpfel");
    });
    expect(output).toBe(
      previous.replace('"value": "Apfel"', '"value": "Äpfel"'),
    );
  });

  test("the result compiles with Xcode", async () => {
    const output = await reexport(xcode, (data) => {
      setText(data, "%lld items", "de", "%1$lld Stück", "one");
      setText(data, "cart", "en", "You have %1$lld items!", "other");
      removeBundle(data, "apple");
    });
    compileWithXcode(output);
  });

  test("saveProjectToDirectory only changes the edited translation", async () => {
    const directory = fs.mkdtempSync(join(tmpdir(), "inlang-xcstrings-keep-"));
    const file = join(directory, "Localizations", "Localizable.xcstrings");
    fs.mkdirSync(join(directory, "Localizations"));
    fs.writeFileSync(file, xcode);
    const project = await loadProjectInMemory({
      blob: await newProject({ settings }),
      providePlugins: [plugin as any],
    });
    try {
      await project.importFiles({
        pluginKey: plugin.key,
        files: [{ locale: "en", content: encode(xcode) }],
      });
      const projectPath = join(directory, "project.inlang");
      await saveProjectToDirectory({
        fs: fs.promises,
        project,
        path: projectPath,
      });
      expect(fs.readFileSync(file, "utf-8")).toBe(xcode);

      const message = await project.db
        .selectFrom("inlang_message")
        .where("bundle_id", "=", "apple")
        .where("locale", "=", "de")
        .select("id")
        .executeTakeFirstOrThrow();
      await project.db
        .updateTable("inlang_variant")
        .where("message_id", "=", message.id)
        .set({ pattern: [{ type: "text", value: "Äpfel" }] })
        .execute();
      await saveProjectToDirectory({
        fs: fs.promises,
        project,
        path: projectPath,
      });
      expect(fs.readFileSync(file, "utf-8")).toBe(
        xcode.replace('"value" : "Apfel"', '"value" : "Äpfel"'),
      );
    } finally {
      await project.close();
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  test("project.exportFiles passes the existing catalog through", async () => {
    const project = await loadProjectInMemory({
      blob: await newProject({ settings }),
      providePlugins: [plugin as any],
    });
    try {
      await project.importFiles({
        pluginKey: plugin.key,
        files: [{ locale: "en", content: encode(xcode) }],
      });
      const [file] = await project.exportFiles({
        pluginKey: plugin.key,
        files: [{ path, locale: "en", content: encode(xcode) }],
      });
      expect(decode(file!.content)).toBe(xcode);
    } finally {
      await project.close();
    }
  });
});

type Data = {
  bundles: any[];
  messages: any[];
  variants: any[];
};

async function reexport(previous: string, edit?: (data: Data) => void) {
  const data = await importCatalog(previous);
  edit?.(data);
  const [file] = await plugin.exportFiles!({
    settings,
    ...data,
    files: [{ path, locale: "en", content: encode(previous) }],
  });
  const output = decode(file!.content);
  // the plugin reads the result as the full export
  expect(await exportWithoutFiles(await importCatalog(output))).toEqual(
    await exportWithoutFiles(data),
  );
  return output;
}

async function exportWithoutFiles(data: Data) {
  const [file] = await plugin.exportFiles!({ settings, ...data });
  return JSON.parse(decode(file!.content));
}

async function importCatalog(content: string): Promise<Data> {
  const imported = await plugin.importFiles!({
    settings,
    files: [{ locale: "en", content: encode(content) }],
  });
  const messages = imported.messages.map((message) => ({
    ...message,
    id: `${message.bundleId}-${message.locale}`,
  }));
  const variants = imported.variants.map((variant) => ({
    ...variant,
    messageId: `${variant.messageBundleId}-${variant.messageLocale}`,
    id: `${variant.messageBundleId}-${variant.messageLocale}-${JSON.stringify(variant.matches)}`,
  }));
  const byId = (a: { id?: string }, b: { id?: string }) =>
    a.id! < b.id! ? -1 : a.id! > b.id! ? 1 : 0;
  return {
    bundles: [...imported.bundles].sort(byId),
    messages: messages.sort(byId),
    variants: variants.sort(byId),
  };
}

function findVariant(
  data: Data,
  bundleId: string,
  locale: string,
  match?: string,
) {
  const variant = data.variants.find(
    (variant) =>
      variant.messageId === `${bundleId}-${locale}` &&
      (match === undefined ||
        (match === "other"
          ? variant.matches[0]?.type === "catchall-match"
          : variant.matches[0]?.value === match)),
  );
  if (!variant) throw new Error(`no variant ${bundleId} ${locale} ${match}`);
  return variant;
}

/** Sets the pattern of a variant to text and `%1$@`-style printf arguments. */
function setText(
  data: Data,
  bundleId: string,
  locale: string,
  text: string,
  match?: string,
) {
  const variant = findVariant(data, bundleId, locale, match);
  variant.pattern = text
    .split(/(%\d+\$[a-z@]+)/)
    .filter((part) => part !== "")
    .map((part) => {
      const found = /^%(\d+)\$([a-z@]+)$/.exec(part);
      if (!found) return { type: "text", value: part };
      return {
        type: "expression",
        arg: { type: "variable-reference", name: `arg${found[1]}` },
        annotation: {
          type: "function-reference",
          name: "apple-printf",
          options: [
            { name: "specifier", value: { type: "literal", value: found[2] } },
            { name: "position", value: { type: "literal", value: found[1] } },
          ],
        },
      };
    });
}

function removeBundle(data: Data, bundleId: string) {
  data.bundles = data.bundles.filter((bundle) => bundle.id !== bundleId);
  const messageIds = new Set(
    data.messages
      .filter((message) => message.bundleId === bundleId)
      .map((message) => message.id),
  );
  data.messages = data.messages.filter(
    (message) => message.bundleId !== bundleId,
  );
  data.variants = data.variants.filter(
    (variant) => !messageIds.has(variant.messageId),
  );
}

function compileWithXcode(content: string) {
  if (process.platform !== "darwin") return;
  const directory = fs.mkdtempSync(join(tmpdir(), "inlang-xcstrings-"));
  const input = join(directory, "Localizable.xcstrings");
  fs.writeFileSync(input, content);
  execFileSync("xcrun", [
    "xcstringstool",
    "compile",
    input,
    "--output-directory",
    directory,
  ]);
  fs.rmSync(directory, { recursive: true, force: true });
}

function encode(value: string) {
  return new TextEncoder().encode(value);
}
function decode(value: Uint8Array) {
  return new TextDecoder("utf-8", { ignoreBOM: true }).decode(value);
}
